export const VALIDATE_FORM = 'VALIDATE_FORM'
export const VALIDATE_FORM_SUCCESS = 'VALIDATE_FORM_SUCCESS'
export const VALIDATE_FORM_FAILED = 'VALIDATE_FORM_FAILED'

export const ADD_RECORD = 'ADD_RECORD'
export const ADD_RECORD_SUCCESS = 'ADD_RECORD_SUCCESS'
export const ADD_RECORD_FAILED = 'ADD_RECORD_FAILED'
export const ADD_NAME = 'ADD_NAME'
