export const VALIDATE_FORM = 'VALIDATE_FORM'
export const VALIDATE_FORM_SUCCESS = 'VALIDATE_FORM_SUCCESS'
export const VALIDATE_FORM_FAILED = 'VALIDATE_FORM_FAILED'

export const ADD_MEASURE = 'ADD_MEASURE'
export const ADD_MEASURE_SUCCESS = 'ADD_MEASURE_SUCCESS'
export const ADD_MEASURE_FAILED = 'ADD_MEASURE_FAILED'
export const ADD_NAME = 'ADD_NAME'
